### ISSUE TITLE
Build issue on Windows

### ISSUE THREAD

**Issue by cgohlke** [amueller/slic-python#1]
Thank you for sharing this wrapper!
The master branch does not build on Windows unless the file `SLIC.cpp` is renamed, e.g. to `_SLIC.cpp`. Cython fails to create `slic.cpp` when `SLIC.cpp` exists because the Windows filesystem is case insensitive.

**Comment by amueller** [comment]
Thanks for the feedback. Will do a patch soon, I'm just in the middle of releasing scikit-learn.

**Comment by amueller** [comment]
Fixed. I renamed `slic.pyx`, not `SLIC.cpp` since I didn't want to rename other peoples files (not sure how sane that is).

**Comment by cgohlke** [comment]
Thanks, that works well.
