### ISSUE TITLE
How can I compile in Windows OS?

### ISSUE THREAD

**Issue by lee88688** [amueller/slic-python#5]
Hi, I clone the code and complie it in windows, but some error(unicode error) occurred. Can this be compiled in Windows?

**Comment by amueller** [comment]
Hey. I have not tried. I'd recommend you use scikit-image instead which has its own implementation of slic.

**Comment by lee88688** [comment]
I use skimage previously. But I find it is to slow. I have tried yours in linux and the speed is much faster. So I decide to use  this.

**Comment by amueller** [comment]
That's odd. When I benchmarked this (when I wrote the skimage implementation), skimage was pretty comparable. If it is not any more, maybe open an issue on the skimage tracker with a benchmark?

**Comment by amueller** [comment]
Generally you should be able to build this on windows, but I can't really help you with the specifics.

**Comment by lee88688** [comment]
thanks, I would try it some time.
